In [1]:
import pandas as pd
df = pd.read_csv('../data/processed/matches_clean.csv')
df["date"] = pd.to_datetime(df["date"])
df.head(5)

,team1,team2,venue,toss_winner,toss_decision,winner,date
0,New Zealand,Australia,Eden Park,Australia,bat,Australia,2005-02-17
1,England,Australia,The Rose Bowl,England,bat,England,2005-06-13
2,South Africa,New Zealand,New Wanderers Stadium,New Zealand,field,New Zealand,2005-10-21
3,Australia,South Africa,"Brisbane Cricket Ground, Woolloongabba",Australia,bat,Australia,2006-01-09
4,South Africa,Australia,New Wanderers Stadium,South Africa,bat,South Africa,2006-02-24

In [2]:
clean_df = pd.read_csv("../data/processed/matches_clean.csv")

clean_df["date"] = pd.to_datetime(clean_df["date"])

print(clean_df["date"].is_monotonic_increasing)

True

In [3]:
df = pd.read_csv("../data/processed/matches_clean.csv")

df["date"] = pd.to_datetime(df["date"])

df = df.sort_values("date").reset_index(drop=True)

print(df[["date"]].head())
df[["date"]].tail()

        date
0 2005-02-17
1 2005-06-13
2 2005-10-21
3 2006-01-09
4 2006-02-24

           date
5230 2026-06-08
5231 2026-06-08
5232 2026-06-09
5233 2026-06-09
5234 2026-06-09

In [4]:
print(df["date"].is_monotonic_increasing)

True

In [5]:
df.to_csv(
    "../data/processed/matches_clean.csv",
    index=False
)

In [6]:
df[["date", "team1", "team2", "winner"]].head(5)

        date         team1         team2        winner
0 2005-02-17   New Zealand     Australia     Australia
1 2005-06-13       England     Australia       England
2 2005-10-21  South Africa   New Zealand   New Zealand
3 2006-01-09     Australia  South Africa     Australia
4 2006-02-24  South Africa     Australia  South Africa

In [ ]:
row = 100

current_match = df.iloc[row]
current_match = df.iloc[row]

team1 = current_match["team1"]

team2 = current_match["team2"]

previous_matches = df.iloc[:row]

team1_matches = previous_matches[
    (previous_matches["team1"] == team1)
    |
    (previous_matches["team2"] == team1)
]


print(team1_matches)

          team1        team2                         venue  toss_winner  \
5       England    Sri Lanka                 The Rose Bowl    Sri Lanka
8   New Zealand    Sri Lanka               Westpac Stadium  New Zealand
9   New Zealand    Sri Lanka                     Eden Park  New Zealand
22        Kenya    Sri Lanka         New Wanderers Stadium        Kenya
24  New Zealand    Sri Lanka         New Wanderers Stadium  New Zealand
29     Pakistan    Sri Lanka         New Wanderers Stadium    Sri Lanka
32   Bangladesh    Sri Lanka         New Wanderers Stadium   Bangladesh
35    Australia    Sri Lanka                      Newlands    Australia
55     Pakistan    Sri Lanka  Maple Leaf North-West Ground     Pakistan
56     Pakistan    Sri Lanka  Maple Leaf North-West Ground    Sri Lanka
61    Sri Lanka        India           R Premadasa Stadium    Sri Lanka
75    Australia    Sri Lanka                  Trent Bridge    Sri Lanka
80    Sri Lanka  West Indies                  Trent Bridge  West Indies
83     Pakistan    Sri Lanka                        Lord's    Sri Lanka
87      Ireland    Sri Lanka                        Lord's    Sri Lanka
92  New Zealand    Sri Lanka                  Trent Bridge    Sri Lanka
95    Sri Lanka  West Indies               Kennington Oval  West Indies
97     Pakistan    Sri Lanka                        Lord's    Sri Lanka

    toss_decision       winner       date  team1_matches_played  \
5               1    Sri Lanka 2006-06-15                     1
8               1    Sri Lanka 2006-12-22                     2
9               0  New Zealand 2006-12-26                     3
22              0    Sri Lanka 2007-09-14                     3
24              1    Sri Lanka 2007-09-15                     5
29              0     Pakistan 2007-09-17                     4
32              0    Sri Lanka 2007-09-18                     5
35              0    Australia 2007-09-20                     9
55              0     Pakistan 2008-10-11                    10
56              0    Sri Lanka 2008-10-13                    11
61              1        India 2009-02-10                    10
75              0    Sri Lanka 2009-06-08                    22
80              0    Sri Lanka 2009-06-10                    12
83              1    Sri Lanka 2009-06-12                    15
87              1    Sri Lanka 2009-06-14                     4
92              1    Sri Lanka 2009-06-16                    23
95              0    Sri Lanka 2009-06-19                    16
97              1     Pakistan 2009-06-21                    19

    team1_win_rate  team1_form_5  ...  team2_win_rate  team2_form_5  \
5         1.000000             1  ...        0.000000             0
8         0.500000             1  ...        1.000000             1
9         0.333333             1  ...        1.000000             2
22        0.000000             0  ...        0.666667             2
24        0.600000             3  ...        0.750000             3
29        1.000000             4  ...        0.800000             4
32        0.400000             2  ...        0.666667             3
35        0.555556             3  ...        0.714286             3
55        0.900000             4  ...        0.625000             3
56        0.909091             4  ...        0.555556             2
61        0.600000             2  ...        0.750000             4
75        0.500000             1  ...        0.545455             2
80        0.583333             2  ...        0.500000             3
83        0.800000             3  ...        0.615385             3
87        0.500000             2  ...        0.642857             4
92        0.434783             3  ...        0.666667             4
95        0.687500             5  ...        0.500000             3
97        0.789474             4  ...        0.705882             5

    team1_h2h_wins  team2_h2h_wins  team1_venue_matches  team1_venue_win_rate  \
5                0               0                    1              1.000000
8                0               0                    0              0.000000
9                0               1                    1              0.000000
22               0               0                    0              0.000000
24               1               1                    1              1.000000
29               0               0                    0              0.000000
32               0               0                    1              1.000000
35               0               0                    3              0.666667
55               1               0                    0              0.000000
56               2               0                    1              1.000000
61               0               0                    0              0.000000
75               1               0                    0              0.000000
80               0               0                    1              1.000000
83               2               1                    1              1.000000
87               0               0                    0              0.000000
92               1               2                    1              1.000000
95               1               0                    0              0.000000
97               2               2                    2              0.500000

    team2_venue_matches  team2_venue_win_rate  team1_won_toss  team2_won_toss
5                     0              0.000000               0               1
8                     0              0.000000               1               0
9                     0              0.000000               1               0
22                    0              0.000000               1               0
24                    1              1.000000               1               0
29                    2              1.000000               0               1
32                    3              0.666667               1               0
35                    0              0.000000               1               0
55                    0              0.000000               1               0
56                    1              0.000000               0               1
61                    0              0.000000               1               0
75                    0              0.000000               0               1
80                    0              0.000000               0               1
83                    0              0.000000               0               1
87                    1              1.000000               0               1
92                    2              1.000000               0               1
95                    5              0.600000               0               1
97                    2              1.000000               0               1

[18 rows x 21 columns]

In [8]:

team2 = current_match["team2"]


team2_matches = previous_matches[
    (previous_matches["team1"] == team2)
    |
    (previous_matches["team2"] == team2)
]

# print(team2_matches)

In [9]:
print(f"Team 1: {team1}")

matches_played = len(team1_matches)
print(f"Matches played: {matches_played}")

wins = team1_matches["winner"] == team1
wins = wins.sum()
print(f"Wins: {wins}")

win_rate = wins/matches_played
print(f"Win Rate: {win_rate}")

last5 = team1_matches.tail(5)
print(f"Last 5 Matches:\n{last5[['date', 'winner', 'team1', 'team2']]}")

team_form = last5["winner"] == team1
team_form = team_form.sum()
print(f"Team Form (Last 5): {team_form}")

print(f"Team 2: {team2}")

matches_played = len(team2_matches)
print(f"Matches played: {matches_played}")

wins = team2_matches["winner"] == team2
wins = wins.sum()
print(f"Wins: {wins}")

win_rate = wins/matches_played
print(f"Win Rate: {win_rate}")

last5 = team2_matches.tail(5)
print(f"Last 5 Matches:\n{last5[['date', 'winner' , 'team1', 'team2']]}")

team_form = last5["winner"] == team2
team_form = team_form.sum()
print(f"Team Form (Last 5): {team_form}")

Team 1: Sri Lanka
Matches played: 18
Wins: 12
Win Rate: 0.6666666666666666
Last 5 Matches:
         date     winner        team1        team2
83 2009-06-12  Sri Lanka     Pakistan    Sri Lanka
87 2009-06-14  Sri Lanka      Ireland    Sri Lanka
92 2009-06-16  Sri Lanka  New Zealand    Sri Lanka
95 2009-06-19  Sri Lanka    Sri Lanka  West Indies
97 2009-06-21   Pakistan     Pakistan    Sri Lanka
Team Form (Last 5): 4
Team 2: Pakistan
Matches played: 20
Wins: 16
Win Rate: 0.8
Last 5 Matches:
         date     winner        team1         team2
83 2009-06-12  Sri Lanka     Pakistan     Sri Lanka
85 2009-06-13   Pakistan  New Zealand      Pakistan
90 2009-06-15   Pakistan      Ireland      Pakistan
93 2009-06-18   Pakistan     Pakistan  South Africa
97 2009-06-21   Pakistan     Pakistan     Sri Lanka
Team Form (Last 5): 4

In [10]:
def get_team_stats(team , previous_matches):
    
    team_matches = previous_matches[(previous_matches["team1"] == team) | (previous_matches["team2"] == team)]
    
    matches_played = len(team_matches)

    wins = (team_matches["winner"] == team).sum()

    if matches_played == 0:
        win_rate = 0
    else:
        win_rate = wins / matches_played

    last5 = team_matches.tail(5)

    team_form = (last5["winner"] == team).sum()

    return {
    "matches_played": matches_played,
    "wins": wins,
    "win_rate": win_rate,
    "form_5": team_form
}

In [11]:
team1_stats = get_team_stats(team1, previous_matches)

team1_winrate = team1_stats["win_rate"]
team1_form = team1_stats["form_5"]

print(team1_stats)
print(f"Team 1 Win Rate: {team1_winrate}")
print(f"Team 1 Form: {team1_form}")

{'matches_played': 18, 'wins': np.int64(12), 'win_rate': np.float64(0.6666666666666666), 'form_5': np.int64(4)}
Team 1 Win Rate: 0.6666666666666666
Team 1 Form: 4

In [12]:
team2_stats = get_team_stats(team2, previous_matches)

team2_winrate = team2_stats["win_rate"]
team2_form = team2_stats["form_5"]

print(team2_stats)
print(f"Team 2 Win Rate: {team2_winrate}")
print(f"Team 2 Form: {team2_form}")
print

{'matches_played': 20, 'wins': np.int64(16), 'win_rate': np.float64(0.8), 'form_5': np.int64(4)}
Team 2 Win Rate: 0.8
Team 2 Form: 4

In [13]:
team1_matches_played_list = []
team1_win_rate_list = []
team1_form_5_list = []

team2_matches_played_list = []
team2_win_rate_list = []
team2_form_5_list = []

for row in range(len(df)):
    current_match = df.iloc[row]

    team1 = current_match["team1"]
    team2 = current_match["team2"]

    previous_matches = df.iloc[:row]

    team1_stats = get_team_stats(team1, previous_matches)

    team2_stats = get_team_stats(team2, previous_matches)

    team1_matches_played_list.append(
    team1_stats["matches_played"]
    )

    team1_win_rate_list.append(
    team1_stats["win_rate"]
    )

    team1_form_5_list.append(
    team1_stats["form_5"]
    )

    team2_matches_played_list.append(
    team2_stats["matches_played"]
    )

    team2_win_rate_list.append(
    team2_stats["win_rate"]
    )

    team2_form_5_list.append(
    team2_stats["form_5"]
    )
# print(len(team1_matches_played_list))
# print(len(team1_win_rate_list))
# print(len(team1_form_5_list))

# print(len(df))
df["team1_matches_played"] = team1_matches_played_list
df["team1_win_rate"] = team1_win_rate_list
df["team1_form_5"] = team1_form_5_list

df["team2_matches_played"] = team2_matches_played_list
df["team2_win_rate"] = team2_win_rate_list
df["team2_form_5"] = team2_form_5_list

df.head(5)

,team1,team2,venue,toss_winner,toss_decision,winner,date,team1_matches_played,team1_win_rate,team1_form_5,team2_matches_played,team2_win_rate,team2_form_5
0,New Zealand,Australia,Eden Park,Australia,bat,Australia,2005-02-17,0,0.0,0,0,0.000000,0
1,England,Australia,The Rose Bowl,England,bat,England,2005-06-13,0,0.0,0,1,1.000000,1
2,South Africa,New Zealand,New Wanderers Stadium,New Zealand,field,New Zealand,2005-10-21,0,0.0,0,1,0.000000,0
3,Australia,South Africa,"Brisbane Cricket Ground, Woolloongabba",Australia,bat,Australia,2006-01-09,2,0.5,1,1,0.000000,0
4,South Africa,Australia,New Wanderers Stadium,South Africa,bat,South Africa,2006-02-24,2,0.0,0,3,0.666667,2

In [14]:
df.to_csv(
    "../data/processed/matches_features_v1.csv",
    index=False
)

In [15]:
rows = 100

current_match = df.iloc[rows]
previous_matches = df.iloc[:100]

team1 = current_match["team1"]
team2 = current_match["team2"]

h2h_match = previous_matches[
    ((previous_matches["team1"] == team1) & (previous_matches["team2"] == team2)) |
    ((previous_matches["team1"] == team2) & (previous_matches["team2"] == team1))
]
print(h2h_match[["date","team1","team2","winner"]])

h2h_t1_wins = (h2h_match["winner"] == team1).sum()
h2h_t2_wins = (h2h_match["winner"] == team2).sum()

print(f"Team 1 H2H Wins: {h2h_t1_wins}")
print(f"Team 2 H2H Wins: {h2h_t2_wins}")

         date     team1      team2     winner
29 2007-09-17  Pakistan  Sri Lanka   Pakistan
55 2008-10-11  Pakistan  Sri Lanka   Pakistan
56 2008-10-13  Pakistan  Sri Lanka  Sri Lanka
83 2009-06-12  Pakistan  Sri Lanka  Sri Lanka
97 2009-06-21  Pakistan  Sri Lanka   Pakistan
Team 1 H2H Wins: 2
Team 2 H2H Wins: 3

In [16]:
def h2h_match_stats(team1, team2, previous_matches):

    h2h_match = previous_matches[
     ((previous_matches["team1"] == team1) & (previous_matches["team2"] == team2)) |
    ((previous_matches["team1"] == team2) & (previous_matches["team2"] == team1))
    ]
    
    h2h_t1_wins = (h2h_match["winner"] == team1).sum()
    h2h_t2_wins = (h2h_match["winner"] == team2).sum()
    return {
        "team1_h2h_wins": h2h_t1_wins,
        "team2_h2h_wins": h2h_t2_wins
    }


row = 100

current_match = df.iloc[row]

team1 = current_match["team1"]
team2 = current_match["team2"]

previous_matches = df.iloc[:row]

h2h_stats = h2h_match_stats(
    team1,
    team2,
    previous_matches
)

print(h2h_stats)

{'team1_h2h_wins': np.int64(2), 'team2_h2h_wins': np.int64(3)}

In [17]:
h2h_team1_wins_list = []
h2h_team2_wins_list = []
for row in range(len(df)):

    current_matches = df.iloc[row]
    
    previous_matches = df.iloc[:row]
    
    team1 = current_matches["team1"]
    team2 = current_matches["team2"]

    h2h_stats = h2h_match_stats(team1 ,team2, previous_matches)

    h2h_team1_wins_list.append(h2h_stats["team1_h2h_wins"])
    h2h_team2_wins_list.append(h2h_stats["team2_h2h_wins"])

In [18]:
print(len(h2h_team1_wins_list))
print(len(h2h_team2_wins_list))

5235
5235

In [19]:
df["team1_h2h_wins"] = h2h_team1_wins_list
df["team2_h2h_wins"] = h2h_team2_wins_list

# df[[
#     "team1",
#     "team2",
#     "team1_h2h_wins",
#     "team2_h2h_wins"
# ]].head()

df.head()

,team1,team2,venue,toss_winner,toss_decision,winner,date,team1_matches_played,team1_win_rate,team1_form_5,team2_matches_played,team2_win_rate,team2_form_5,team1_h2h_wins,team2_h2h_wins
0,New Zealand,Australia,Eden Park,Australia,bat,Australia,2005-02-17,0,0.0,0,0,0.000000,0,0,0
1,England,Australia,The Rose Bowl,England,bat,England,2005-06-13,0,0.0,0,1,1.000000,1,0,0
2,South Africa,New Zealand,New Wanderers Stadium,New Zealand,field,New Zealand,2005-10-21,0,0.0,0,1,0.000000,0,0,0
3,Australia,South Africa,"Brisbane Cricket Ground, Woolloongabba",Australia,bat,Australia,2006-01-09,2,0.5,1,1,0.000000,0,0,0
4,South Africa,Australia,New Wanderers Stadium,South Africa,bat,South Africa,2006-02-24,2,0.0,0,3,0.666667,2,0,1

In [20]:
df.to_csv(
    "../data/processed/matches_features_v1.csv",
    index=False
)

In [21]:
df["venue"] = df["venue"].replace({
    "R.Premadasa Stadium, Khettarama": "R Premadasa Stadium",
    "R Premadasa Stadium, Colombo": "R Premadasa Stadium"
})
df[df["venue"].str.contains("Premadasa", case=False)]["venue"].unique()

df["venue"].value_counts().head(20)
df[df["venue"].str.contains("Premadasa", case=False, na=False)]["venue"].unique()

array(['R Premadasa Stadium'], dtype=object)

In [22]:
row = 100

current_match = df.iloc[row]

team1 = current_match["team1"]
team2 = current_match["team2"]
venue = current_match["venue"]

previous_matches = df.iloc[:row]

team1_venue_matches = previous_matches[
    (
        (previous_matches["team1"] == team1) |
        (previous_matches["team2"] == team1)
    )
    &
    (previous_matches["venue"] == venue)
]

print(team1)
print(venue)

print(
    team1_venue_matches[
        ["date", "team1", "team2", "venue", "winner"]
    ]
)



team2_venue_matches = previous_matches[
    (
        (previous_matches["team1"] == team2) |
        (previous_matches["team2"] == team2)
    )
    &
    (previous_matches["venue"] == venue)
]

print(team2)
print(venue)

print(
    team2_venue_matches[
        ["date", "team1", "team2", "venue", "winner"]
    ]
)

Sri Lanka
R Premadasa Stadium
         date      team1  team2                venue winner
61 2009-02-10  Sri Lanka  India  R Premadasa Stadium  India
Pakistan
R Premadasa Stadium
Empty DataFrame
Columns: [date, team1, team2, venue, winner]
Index: []

In [23]:
venue_matches = previous_matches[
    previous_matches["venue"] == venue
]

print(len(venue_matches))
print(
    venue_matches[
        ["date","team1","team2","winner"]
    ]
)

1
         date      team1  team2 winner
61 2009-02-10  Sri Lanka  India  India

In [24]:
def get_venue_stats(team, venue, previous_matches):
    

    team_venue_matches = previous_matches[
    (
        (previous_matches["team1"] == team) |
        (previous_matches["team2"] == team)
    )
    &
    (previous_matches["venue"] == venue)
    ]
    
    matches_played = len(team_venue_matches)

    wins = (team_venue_matches["winner"] == team).sum()

    venue_win_rate = wins / matches_played


    if matches_played == 0:
        return{
        "venue_matches": 0,
        "venue_win_rate": 0
    }


    return{
        "venue_matches" : matches_played,
        "venue_win_rate" : venue_win_rate

    }


venue_stats = get_venue_stats(
    team1,
    venue,
    previous_matches
)

print(venue_stats)

{'venue_matches': 1, 'venue_win_rate': np.float64(0.0)}

In [25]:
team1_venue_matches_list = []
team1_venue_win_rate_list = []

team2_venue_matches_list = []
team2_venue_win_rate_list = []

for row in range(len(df)):
    current_match = df.iloc[row]

    previous_matches = df.iloc[:row]

    team1 = current_match["team1"]
    team2 = current_match["team2"]
    venue = current_match["venue"]

    team1_venue_stats = get_venue_stats(
    team1,
    venue,
    previous_matches
    )

    team2_venue_stats = get_venue_stats(
    team2,
    venue,
    previous_matches
    )

    team1_venue_matches_list.append(
    team1_venue_stats["venue_matches"]
)

    team1_venue_win_rate_list.append(
    team1_venue_stats["venue_win_rate"]
)

    team2_venue_matches_list.append(
    team2_venue_stats["venue_matches"]
)

    team2_venue_win_rate_list.append(
    team2_venue_stats["venue_win_rate"]
)

print(len(team1_venue_matches_list))
print(len(team1_venue_win_rate_list))
print(len(team2_venue_matches_list))
print(len(team2_venue_win_rate_list))

print(len(df))

C:\Users\SURYANSH\AppData\Local\Temp\ipykernel_13240\2881968812.py:17: RuntimeWarning: invalid value encountered in scalar divide
  venue_win_rate = wins / matches_played

5235
5235
5235
5235
5235

In [26]:
df["team1_venue_matches"] = team1_venue_matches_list
df["team1_venue_win_rate"] = team1_venue_win_rate_list 

df["team2_venue_matches"] = team2_venue_matches_list
df["team2_venue_win_rate"] = team2_venue_win_rate_list 

df.head(30)

,team1,team2,venue,toss_winner,toss_decision,winner,date,team1_matches_played,team1_win_rate,team1_form_5,team2_matches_played,team2_win_rate,team2_form_5,team1_h2h_wins,team2_h2h_wins,team1_venue_matches,team1_venue_win_rate,team2_venue_matches,team2_venue_win_rate
0,New Zealand,Australia,Eden Park,Australia,bat,Australia,2005-02-17,0,0.000000,0,0,0.000000,0,0,0,0,0.000000,0,0.0
1,England,Australia,The Rose Bowl,England,bat,England,2005-06-13,0,0.000000,0,1,1.000000,1,0,0,0,0.000000,0,0.0
2,South Africa,New Zealand,New Wanderers Stadium,New Zealand,field,New Zealand,2005-10-21,0,0.000000,0,1,0.000000,0,0,0,0,0.000000,0,0.0
3,Australia,South Africa,"Brisbane Cricket Ground, Woolloongabba",Australia,bat,Australia,2006-01-09,2,0.500000,1,1,0.000000,0,0,0,0,0.000000,0,0.0
4,South Africa,Australia,New Wanderers Stadium,South Africa,bat,South Africa,2006-02-24,2,0.000000,0,3,0.666667,2,0,1,1,0.000000,0,0.0
5,England,Sri Lanka,The Rose Bowl,Sri Lanka,bat,Sri Lanka,2006-06-15,1,1.000000,1,0,0.000000,0,0,0,1,1.000000,0,0.0
6,England,Pakistan,County Ground,England,bat,Pakistan,2006-08-28,2,0.500000,1,0,0.000000,0,0,0,0,0.000000,0,0.0
7,South Africa,India,New Wanderers Stadium,South Africa,bat,India,2006-12-01,3,0.333333,1,0,0.000000,0,0,0,2,0.500000,0,0.0
8,New Zealand,Sri Lanka,Westpac Stadium,New Zealand,bat,Sri Lanka,2006-12-22,2,0.500000,1,1,1.000000,1,0,0,0,0.000000,0,0.0
9,New Zealand,Sri Lanka,Eden Park,New Zealand,field,New Zealand,2006-12-26,3,0.333333,1,2,1.000000,2,0,1,1,0.000000,0,0.0
10,Australia,England,Sydney Cricket Ground,Australia,bat,Australia,2007-01-09,4,0.500000,2,3,0.333333,1,0,1,0,0.000000,0,0.0
11,England,West Indies,Kennington Oval,West Indies,bat,West Indies,2007-06-28,4,0.250000,1,0,0.000000,0,0,0,0,0.000000,0,0.0
12,England,West Indies,Kennington Oval,West Indies,bat,England,2007-06-29,5,0.200000,1,1,1.000000,1,0,1,1,0.000000,1,1.0
13,Kenya,Bangladesh,Gymkhana Club Ground,Bangladesh,field,Bangladesh,2007-09-01,0,0.000000,0,0,0.000000,0,0,0,0,0.000000,0,0.0
14,Bangladesh,Pakistan,Gymkhana Club Ground,Bangladesh,field,Pakistan,2007-09-02,1,1.000000,1,1,1.000000,1,0,0,1,1.000000,0,0.0
15,Kenya,Pakistan,Gymkhana Club Ground,Kenya,bat,Pakistan,2007-09-04,1,0.000000,0,2,1.000000,2,0,0,1,0.000000,1,1.0
16,South Africa,West Indies,New Wanderers Stadium,South Africa,field,South Africa,2007-09-11,4,0.250000,1,2,0.500000,1,0,0,3,0.333333,0,0.0
17,Kenya,New Zealand,Kingsmead,New Zealand,field,New Zealand,2007-09-12,2,0.000000,0,4,0.500000,2,0,0,0,0.000000,0,0.0
18,Australia,Zimbabwe,Newlands,Australia,bat,Zimbabwe,2007-09-12,5,0.600000,3,0,0.000000,0,0,0,0,0.000000,0,0.0
19,Pakistan,Scotland,Kingsmead,Scotland,field,Pakistan,2007-09-12,3,1.000000,3,0,0.000000,0,0,0,0,0.000000,0,0.0
20,Bangladesh,West Indies,New Wanderers Stadium,Bangladesh,field,Bangladesh,2007-09-13,2,0.500000,1,3,0.333333,1,0,0,0,0.000000,1,0.0
21,England,Zimbabwe,Newlands,England,bat,England,2007-09-13,6,0.333333,1,1,1.000000,1,0,0,0,0.000000,1,1.0
22,Kenya,Sri Lanka,New Wanderers Stadium,Kenya,field,Sri Lanka,2007-09-14,3,0.000000,0,3,0.666667,2,0,0,0,0.000000,0,0.0
23,Australia,England,Newlands,England,bat,Australia,2007-09-14,6,0.500000,2,7,0.428571,2,1,1,1,0.000000,1,1.0
24,New Zealand,Sri Lanka,New Wanderers Stadium,New Zealand,bat,Sri Lanka,2007-09-15,5,0.600000,3,4,0.750000,3,1,1,1,1.000000,1,1.0
25,South Africa,Bangladesh,Newlands,South Africa,field,South Africa,2007-09-15,5,0.400000,2,3,0.666667,2,0,0,0,0.000000,0,0.0
26,South Africa,England,Newlands,England,field,South Africa,2007-09-16,6,0.500000,3,8,0.375000,2,0,0,1,1.000000,2,0.5
27,India,New Zealand,New Wanderers Stadium,India,field,New Zealand,2007-09-16,1,1.000000,1,6,0.500000,3,0,0,1,1.000000,2,0.5
28,Australia,Bangladesh,Newlands,Australia,field,Australia,2007-09-16,7,0.571429,3,4,0.500000,2,0,0,2,0.500000,1,0.0
29,Pakistan,Sri Lanka,New Wanderers Stadium,Sri Lanka,field,Pakistan,2007-09-17,4,1.000000,4,5,0.800000,4,0,0,0,0.000000,2,1.0

In [27]:
df.to_csv("../data/processed/matches_features_v1.csv",index=False)

In [30]:
df["team1_won_toss"] = (
    df["team1"] == df["toss_winner"]
).astype(int)

df["team2_won_toss"] = (
    df["team2"] == df["toss_winner"]
).astype(int)

print(df["toss_decision"].unique())

df["toss_decision"] = (
    df["toss_decision"] == "bat"
).astype(int)

df.to_csv(
    "../data/processed/matches_features_v1.csv",
    index=False
)

[1 0]